### PR TITLE
company-mode: add colors for annotations

### PR DESCRIPTION
**Pull request by natto1784**
Before
Before
After
After

### CODE REVIEW

**Comment by NamesCode** [comment]
Looks great, however could you change rosewater to latte?

**Review by NamesCode — CHANGES_REQUESTED** [review]
Looks great, however could you change rosewater to latte?

**Comment by natto1784** [comment]
> Looks great, however could you change rosewater to latte?

sorry, I do not understand what you mean here

**Comment by NamesCode** [comment]
My bad, I meant text

**Comment by natto1784** [comment]
done!

**Comment by natto1784** [comment]
ah well

**Review by NamesCode — APPROVED** [review]
Thanks

**Comment by NamesCode** [comment]
I will merge now

**Pull request merged**
