### PR TITLE
Added stuff

### PR DESCRIPTION
**Pull request by NamesCode**
_Polish_

Feel free to edit stuff

### CODE REVIEW

**Comment by nekowinston** [comment]
Sorry, but I can't accept the PR like this, with the Catwalk showing practically 0 difference between Mocha and Macchiato.

I tweaked some things so it follows the org-wide conventions, please re-take the screenshots **with transparency off**.

**Review by nekowinston — CHANGES_REQUESTED** [review]
Please make Mocha/Macchiato more distinguishable in the composite image.

**Comment by NamesCode** [comment]
Will do

**Comment by NamesCode** [comment]
Done
fixed screenshots

**Review by nekowinston — APPROVED** [review]

**Comment by nekowinston** [comment]
Much better, thank you.

**Pull request merged**
