### PR TITLE
feat: tree-sitter update

### PR DESCRIPTION
**Pull request by LionyxML**
This PR aims to get Emacs Catppuccin theme closer to the neo vim one.

One thing tough, I compared it with the built-in nvchad built-in catppuccin since I was now capable enough to change it to regular without tweaking my nvchad configuration.

As discussed on Discord, minor differences will happen and faces are sadly missing :(

How it looks on regular/test code (Typescript, using typescript-ts-mode): 

Emacs:
Captura de Tela 2023-06-04 às 22 39 38

Nvim:
Captura de Tela 2023-06-04 às 22 40 08

--------- 

How it looks with imports (unfortunately tree-sitter uses the same parameter we use for "const" and "import" keywords), so I just noted it for further revision with a comment.

Emacs:
Captura de Tela 2023-06-04 às 22 40 33

Nvim:
Captura de Tela 2023-06-04 às 22 40 21

--------- 

Regexes were a big red blob before, now  it almost looks like the same:
Emacs:
Captura de Tela 2023-06-04 às 22 44 58

Nvim:
Captura de Tela 2023-06-04 às 22 45 09

### CODE REVIEW

**Comment by NamesCode** [comment]
Lemme check it out now

**Comment by NamesCode** [comment]
Looks good but I don't use Treesitter yet, You'll have to check with Nyx

**Comment by KaranAhlawat** [comment]
Just chipping in, I'd also make sure it's all compliant with the style-guide [here](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md)

It'd be better to have to look different than other editors and be standard compliant than the other way around. Also looking at the JetBrains implementation where it's unclear what to do might be a good idea.

**Comment by nyxkrage** [comment]
:wave: Hey, sorry it's taken a while to get to this. I just want a bit of clarification on some faces

Is string.special is what the regex uses?
What is parts of the language use the attribute and property.definition faces?

Otherwise this looks pretty good

**Comment by LionyxML** [comment]
Thanks for all your kind remarks!

I should've provided a before/after for comparison of each property, my bad.

So, `string.special` change makes this change, I could only reproduce it with regexes:

image

`punctuation.bracket` and `punctuation.delimiter` before and after:

image

`:attribute` was a copy/paste mistake :/ , oops, commiting the change, I think I originally wanted to add the `property`, I'll add it to my commit.

So `:property` and `:property.definition` changes, when declaring objects with key/values pairs and accessing it:
image

Side by side with Neovim (Emacs on the right):
image

As pointed before I was using the catppuccin version  that comes with NVChad (nvim + nvchad: https://github.com/NvChad/NvChad).

I was done and about to hit comment, but I remembered I could also install catppuccin on my nvim from https://github.com/catppuccin/nvim.

Well well gentlemen, we have diffs (left catppuccin original / emacs).
image

Before I submit another commit, could anyone provide me with which one is the right one? Unfortunaly I've got no access to JetBrains :/

**Comment by nyxkrage** [comment]
Can you post the code snippet you've used as a gist, then I'll check up how it looks in JetBrains!

**Comment by LionyxML** [comment]
https://gist.github.com/LionyxML/3d88b6ae9cd5fd64c70ea613488a34b5

**Comment by nyxkrage** [comment]
Okay, the jetbrains javascript highlighting sadly isn't very good
image

However a couple of things
* We should probably not make the properties teal, it sticks out like a sore thumb imo, and I think following catppuccin/nvim, which is lavender i belive, and putting that in the style-guide.
* Looking at the style guide, braces and delimiters should be overlay2 when rainbow-brackets isn't available
* I'm not sure which part has made true and false red, it should stay peach, though I'm unsure if that is a regression from before this PR.

**Comment by LionyxML** [comment]
Sorry I forgot to send you the regex pattern. Can you take a look of how it looks on JB?
``` js 
 const regexString =
  /^[0-9A-Za-z]*[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?].*[0-9a-zA-Z]*$/;
```

So following what you just said, does this look closer to the guideline?
Captura de Tela 2023-06-12 às 20 35 07


About true/false, it looks like it's being set by `...variable.builtin` and/or `...constant.builtin` if we change it both boolean and `console` keywords are changed.
It is now: 
image

I could only change for: 
image
I can change it here in the PR if you want to keep it peach. But on JB console and boolean can be different colors it does not seems to be the case with emacs current tree-sitter 😢 .

Emacs also seems to treat functions that starts with a capital letter as a type (yellow):
image

Buf if we change it to lowercase 
image

It goes for the function font, lol.

If you could please also see how this looks on JB:
image
```js
import React, { useState } from "react";
import { useNavigate } from "react-router";
import { CopyrightLine } from "../../components";
``` 

See, emacs is doing something funny here, just like functions if we capitalize the first letter, it treats as a type (yellow), else it is like normal text.

I'll wait until we close these matters before send another commit :)

**Comment by LionyxML** [comment]
I still have to commit the last changes. I'll to this later today.

**Comment by LionyxML** [comment]
Ok, last commit sets it the way we discussed:

image

**Comment by nyxkrage** [comment]
Looks good! Thanks for the work

**Pull request merged**
