### PR TITLE
Changed background colors for LSP breadcrumb from crust to base issue…

### PR DESCRIPTION
**Pull request by Askath**
Hello, 
I changed the background color for the LSP headings to the base color. 

If there is any issue please let me know (Issue #19)

### CODE REVIEW

**Comment by NamesCode** [comment]
Lemme take a look now

**Comment by NamesCode** [comment]
Currently I cannot find your repo. I will look over the code soon

**Comment by Askath** [comment]
oh yeah, I can't access it either. 
Shall I make a new request?

**Comment by NamesCode** [comment]
Yeah, if you can.

**Pull request closed without merging**
