### PR TITLE
Add difference to modeline

### PR DESCRIPTION
**Pull request by NamesCode**
as brought up by issue#51

### CODE REVIEW

**Review by nyxkrage — CHANGES_REQUESTED** [review]
We should probably also darken the solaire modeline faces

**Comment by NamesCode** [comment]
> We should probably also darken the solaire modeline faces

Does Solaire not inherit from the default?

**Comment by NamesCode** [comment]
I'm unsure if I can darken the Solaire from crust?

**Review by nyxkrage — APPROVED** [review]
Yeah, I think just dimming the foreground is reasonable

**Pull request merged**
